language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
before_install:
  - ruby -v
  - gem install origen
script:
  - origen -v
  - origen m debug
  - origen test -c
  - origen web compile --no-serve
  - origen lint --no-correct
env:
  - ORIGEN_GEM_USE_FROM_SYSTEM=false ORIGEN_GEM_MANAGE_BUNDLER=false
