name: Ruby

on:
  pull_request:
    branches:
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.3.x
    - name: Build and test Origen
      run: |
        gem install bundler -v '< 2'
        bundle install --jobs 4 --retry 3
        origen -v
        origen m debug
        origen test -c
        origen web compile --no-serve
        origen lint --no-correct
